In [10]:
import pandas as pd
import numpy as np
import scipy.stats as stats
import matplotlib.pyplot as plt
from typing import List, Tuple

In [29]:
active_counts_per_epoch_min = 500
minimum_bout_length = 10
maximum_number_consec_inactive_epochs_in_bout = 3
min_non_wearing_length = 20 * 2  # Assuming 30 second epochs
min_complete_day = 8*60*2 # 8hrs per 24 hrs
filepath = "~/Desktop/Desktop/epidemiology_PhD/R/packages/walkboutr/tests/fixtures/"

In [33]:
ActivityEpoch = Tuple[int, int, int]


# General purpose activity sequence builders
def make_active_period(length: int = 1, is_bout: bool = True, non_wearing: bool = False, complete_day: bool = False) -> ActivityEpoch:
    return [(active_counts_per_epoch_min, int(is_bout), 0, False)]*length

def make_inactive_period(length: int = 1, is_bout: bool = False, non_wearing: bool = False, complete_day: bool = False) -> ActivityEpoch:
    return [(0, int(is_bout), bool(non_wearing), bool(complete_day))]*length

def add_date_and_format(counts_and_labels: List[ActivityEpoch]) -> pd.DataFrame:
    dates = pd.date_range(start='2012-04-07',freq="30S", periods = len(counts_and_labels))
    df = pd.DataFrame(data=counts_and_labels, columns=['activity_counts', 'bout', 'non_wearing', 'complete_day'])
    df['time'] = dates
    return df

# Higher level helpers

def make_smallest_bout_window() -> List[ActivityEpoch]:
    return make_active_period(minimum_bout_length)

def make_non_bout_window() -> List[ActivityEpoch]:
    return make_inactive_period(maximum_number_consec_inactive_epochs_in_bout + 1)

def make_smallest_nonwearing_window() -> List[ActivityEpoch]:
    return make_inactive_period(min_non_wearing_length, non_wearing=True)

def make_smallest_complete_day_activity() -> List[ActivityEpoch]:
    return make_active_period(min_complete_day, non_wearing=False)


# Test set makers

def make_smallest_bout():
    counts = (
        make_non_bout_window()
        + make_smallest_bout_window()
        + make_non_bout_window()
    )
    return add_date_and_format(counts)

def make_smallest_bout_with_largest_inactive_period():
    nbw = make_non_bout_window()
    inactive_period = make_inactive_period(maximum_number_consec_inactive_epochs_in_bout,is_bout=True)
    sbw = make_smallest_bout_window()
    halfway = len(sbw) // 2
    
    counts = (
        nbw 
        + sbw[:halfway] + inactive_period + sbw[halfway:]
        + nbw
    )
    return add_date_and_format(counts)

def make_smallest_bout_with_smallest_non_wearing_period():
    counts = (
        make_non_bout_window()
        + make_smallest_bout_window()
        + make_smallest_nonwearing_window()
    )
    return add_date_and_format(counts)

def make_full_day_bout():
    counts = (
        make_non_bout_window()
        + make_smallest_bout_window()
        + make_smallest_complete_day_activity()
    )
    return add_date_and_format(counts)
    
make_smallest_bout_with_smallest_non_wearing_period()

    activity_counts  bout  non_wearing  complete_day                time
0                 0     0            0         False 2012-04-07 00:00:00
1                 0     0            0         False 2012-04-07 00:00:30
2                 0     0            0         False 2012-04-07 00:01:00
3                 0     0            0         False 2012-04-07 00:01:30
4               500     1            0         False 2012-04-07 00:02:00
5               500     1            0         False 2012-04-07 00:02:30
6               500     1            0         False 2012-04-07 00:03:00
7               500     1            0         False 2012-04-07 00:03:30
8               500     1            0         False 2012-04-07 00:04:00
9               500     1            0         False 2012-04-07 00:04:30
10              500     1            0         False 2012-04-07 00:05:00
11              500     1            0         False 2012-04-07 00:05:30
12              500     1            0         False 2012-04-07 00:06:00
13              500     1            0         False 2012-04-07 00:06:30
14                0     0            1         False 2012-04-07 00:07:00
15                0     0            1         False 2012-04-07 00:07:30
16                0     0            1         False 2012-04-07 00:08:00
17                0     0            1         False 2012-04-07 00:08:30
18                0     0            1         False 2012-04-07 00:09:00
19                0     0            1         False 2012-04-07 00:09:30
20                0     0            1         False 2012-04-07 00:10:00
21                0     0            1         False 2012-04-07 00:10:30
22                0     0            1         False 2012-04-07 00:11:00
23                0     0            1         False 2012-04-07 00:11:30
24                0     0            1         False 2012-04-07 00:12:00
25                0     0            1         False 2012-04-07 00:12:30
26                0     0            1         False 2012-04-07 00:13:00
27                0     0            1         False 2012-04-07 00:13:30
28                0     0            1         False 2012-04-07 00:14:00
29                0     0            1         False 2012-04-07 00:14:30
30                0     0            1         False 2012-04-07 00:15:00
31                0     0            1         False 2012-04-07 00:15:30
32                0     0            1         False 2012-04-07 00:16:00
33                0     0            1         False 2012-04-07 00:16:30
34                0     0            1         False 2012-04-07 00:17:00
35                0     0            1         False 2012-04-07 00:17:30
36                0     0            1         False 2012-04-07 00:18:00
37                0     0            1         False 2012-04-07 00:18:30
38                0     0            1         False 2012-04-07 00:19:00
39                0     0            1         False 2012-04-07 00:19:30
40                0     0            1         False 2012-04-07 00:20:00
41                0     0            1         False 2012-04-07 00:20:30
42                0     0            1         False 2012-04-07 00:21:00
43                0     0            1         False 2012-04-07 00:21:30
44                0     0            1         False 2012-04-07 00:22:00
45                0     0            1         False 2012-04-07 00:22:30
46                0     0            1         False 2012-04-07 00:23:00
47                0     0            1         False 2012-04-07 00:23:30
48                0     0            1         False 2012-04-07 00:24:00
49                0     0            1         False 2012-04-07 00:24:30
50                0     0            1         False 2012-04-07 00:25:00
51                0     0            1         False 2012-04-07 00:25:30
52                0     0            1         False 2012-04-07 00:26:00
53                0     0            1         False 2012-04-07 00:26:30

In [32]:
make_smallest_bout().to_csv(f'{filepath}smallest_bout.csv', index=False)
make_smallest_bout_with_largest_inactive_period().to_csv(f'{filepath}smallest_bout_with_largest_inactive_period.csv', index=False)
make_smallest_bout_with_smallest_non_wearing_period().to_csv(f'{filepath}smallest_bout_with_smallest_non_wearing_period.csv', index=False)
make_full_day_bout().to_csv(f'{filepath}smallest_full_day_bout.csv', index=False)

In [61]:
def generate_bout_activity_vector(bout_length: int,
                                 min_active_epochs: int, 
                                 seed: int = 12345):
    np.random.seed(seed)
    if bout_length < min_active_epochs: 
        raise ValueError("Bout length must be greater than number of minimum active epochs")
    dist = stats.bernoulli(p=.5)
    activity_sequence = [0,0,0,0,1]
    zero_counter = 0
    bout_length = bout_length - 2
    min_active_epochs = min_active_epochs - 2
    for i in range(bout_length):
        next_epoch = dist.rvs()
        if next_epoch == 0: 
            zero_counter = zero_counter + 1 
            if zero_counter == 4:
                next_epoch = 1 
                zero_counter = 0
        else: 
            zero_counter = 0
            min_active_epochs = min_active_epochs - 1
            if min_active_epochs == bout_length - i:
                remainder = [1]*(bout_length-i)
                activity_sequence.extend(remainder)
                break
        activity_sequence.append(next_epoch)
        
    activity_sequence.extend([1,0,0,0,0])
    return activity_sequence

In [63]:
# %%timeit
np.array(generate_bout_activity_vector(100, 14))

array([0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0,
       1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0])

In [64]:
def generate_non_bout_activity_vector(vector_length: int,
                                      min_active_epochs:int,
                                      seed: int = 12345): 
    np.random.seed(seed)
    bout_break = [0,0,0,0]
    dist = stats.bernoulli(.75)
    activity_vector = list()
    while len(activity_vector) < vector_length:
        mini_activity_sequence = list(dist.rvs(min_active_epochs - 1))
        activity_vector.extend(mini_activity_sequence + bout_break)
    return activity_vector[:vector_length]

In [65]:
np.array(generate_non_bout_activity_vector(33, 10, 12345))

array([0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1])

In [ ]:
# def generate_person()

In [ ]:
# def generate_dataset()

In [ ]:
# format: assign times and accelemotry values to each of these 0s and 1s

In [ ]:
# final result: Dataset with X number of people, each with Y number of bouts and Z number of nonbouts, 
# that can be run through the walkbout code to label bouts